-- InkluMarket — core schema
-- Domain: PWD livelihood marketplace (buyers, PWD sellers, administrators).
--
-- NOTE: This Supabase project is shared with the wider InkluTrack ecosystem, so
-- every InkluMarket table is namespaced with an `im_` prefix to avoid collisions
-- with other apps' tables (e.g. an existing public.profiles / public.orders).
-- Integer primary keys mirror the original static-demo seed ids so all FKs line up.

begin;

-- ---------------------------------------------------------------------------
-- im_profiles (users)
-- ---------------------------------------------------------------------------
create table if not exists public.im_profiles (
  id              bigint generated by default as identity primary key,
  auth_user_id    uuid unique references auth.users(id) on delete set null,
  name            text not null,
  email           text not null unique,
  role            text not null check (role in ('buyer','seller','admin')),
  disability_type text,
  assistive_needs text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- im_categories (folders)
-- ---------------------------------------------------------------------------
create table if not exists public.im_categories (
  id     text primary key,
  label  text not null,
  folder text not null
);

-- ---------------------------------------------------------------------------
-- im_products
-- ---------------------------------------------------------------------------
create table if not exists public.im_products (
  id          bigint generated by default as identity primary key,
  seller_id   bigint not null references public.im_profiles(id) on delete cascade,
  title       text not null,
  description text,
  base_price  numeric(12,2) not null check (base_price >= 0),
  category    text references public.im_categories(id) on delete set null,
  image       text,
  status      text not null default 'pending' check (status in ('pending','approved','flagged')),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index if not exists idx_im_products_seller   on public.im_products(seller_id);
create index if not exists idx_im_products_category on public.im_products(category);
create index if not exists idx_im_products_status   on public.im_products(status);

-- ---------------------------------------------------------------------------
-- im_product_variants (color + size + stock; unique SKU)
-- ---------------------------------------------------------------------------
create table if not exists public.im_product_variants (
  id         bigint generated by default as identity primary key,
  product_id bigint not null references public.im_products(id) on delete cascade,
  color_name text not null,
  size       text,
  stock_qty  integer not null default 0 check (stock_qty >= 0),
  sku_code   text not null unique
);
create index if not exists idx_im_variants_product on public.im_product_variants(product_id);

-- ---------------------------------------------------------------------------
-- im_product_images (seller-uploaded photos; emoji art is the fallback)
-- ---------------------------------------------------------------------------
create table if not exists public.im_product_images (
  id         bigint generated by default as identity primary key,
  product_id bigint not null references public.im_products(id) on delete cascade,
  url        text not null,
  position   integer not null default 0
);
create index if not exists idx_im_images_product on public.im_product_images(product_id);

-- ---------------------------------------------------------------------------
-- im_orders
-- ---------------------------------------------------------------------------
create table if not exists public.im_orders (
  id           bigint generated by default as identity primary key,
  buyer_id     bigint not null references public.im_profiles(id) on delete cascade,
  total_amount numeric(12,2) not null check (total_amount >= 0),
  order_status text not null default 'pending'
                 check (order_status in ('pending','processing','shipped','delivered','returned')),
  created_at   timestamptz not null default now()
);
create index if not exists idx_im_orders_buyer on public.im_orders(buyer_id);

-- ---------------------------------------------------------------------------
-- im_order_items
-- ---------------------------------------------------------------------------
create table if not exists public.im_order_items (
  id         bigint generated by default as identity primary key,
  order_id   bigint not null references public.im_orders(id) on delete cascade,
  product_id bigint references public.im_products(id) on delete set null,
  variant_id bigint references public.im_product_variants(id) on delete set null,
  quantity   integer not null check (quantity > 0),
  unit_price numeric(12,2) not null check (unit_price >= 0)
);
create index if not exists idx_im_order_items_order   on public.im_order_items(order_id);
create index if not exists idx_im_order_items_product on public.im_order_items(product_id);

-- ---------------------------------------------------------------------------
-- im_product_reviews
-- ---------------------------------------------------------------------------
create table if not exists public.im_product_reviews (
  id           bigint generated by default as identity primary key,
  product_id   bigint not null references public.im_products(id) on delete cascade,
  buyer_id     bigint not null references public.im_profiles(id) on delete cascade,
  rating_score integer not null check (rating_score between 1 and 5),
  comment_text text,
  created_at   timestamptz not null default now(),
  unique (product_id, buyer_id)
);
create index if not exists idx_im_reviews_product on public.im_product_reviews(product_id);

-- ---------------------------------------------------------------------------
-- im_support_tickets + im_ticket_responses
-- ---------------------------------------------------------------------------
create table if not exists public.im_support_tickets (
  id                    bigint generated by default as identity primary key,
  user_id               bigint not null references public.im_profiles(id) on delete cascade,
  subject               text not null,
  description_narrative text not null,
  ticket_status         text not null default 'open'
                          check (ticket_status in ('open','in_progress','resolved')),
  priority_level        text not null default 'medium'
                          check (priority_level in ('low','medium','high')),
  assigned_to           bigint references public.im_profiles(id) on delete set null,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);
create index if not exists idx_im_tickets_user     on public.im_support_tickets(user_id);
create index if not exists idx_im_tickets_assigned on public.im_support_tickets(assigned_to);

create table if not exists public.im_ticket_responses (
  id          bigint generated by default as identity primary key,
  ticket_id   bigint not null references public.im_support_tickets(id) on delete cascade,
  author_role text not null check (author_role in ('buyer','seller','admin')),
  author_id   bigint references public.im_profiles(id) on delete set null,
  message     text not null,
  created_at  timestamptz not null default now()
);
create index if not exists idx_im_responses_ticket on public.im_ticket_responses(ticket_id);

-- ---------------------------------------------------------------------------
-- im_consent_logs (RA 10173) + im_audit_logs
-- ---------------------------------------------------------------------------
create table if not exists public.im_consent_logs (
  id         bigint generated by default as identity primary key,
  user_id    bigint references public.im_profiles(id) on delete cascade,
  action     text not null,
  consent    boolean not null default true,
  purpose    text,
  created_at timestamptz not null default now()
);

create table if not exists public.im_audit_logs (
  id         bigint generated by default as identity primary key,
  actor_id   bigint references public.im_profiles(id) on delete set null,
  actor_role text,
  action     text not null,
  target     text,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- im_theme_settings (global singleton, admin-editable) + im_ui_prefs (per user)
-- ---------------------------------------------------------------------------
create table if not exists public.im_theme_settings (
  id                integer primary key default 1 check (id = 1),
  theme_preset      text not null default 'default',
  color_nav         text,
  color_body        text,
  color_footer      text,
  color_nav_text    text,
  color_footer_text text,
  updated_by        bigint references public.im_profiles(id) on delete set null,
  updated_at        timestamptz not null default now()
);

create table if not exists public.im_ui_prefs (
  user_id      bigint primary key references public.im_profiles(id) on delete cascade,
  contrast     text not null default 'default' check (contrast in ('default','high')),
  theme_preset text,
  updated_at   timestamptz not null default now()
);

commit;
