-- IncluMarket — DB cart, auth→profile trigger, wipe legacy demo rows.

begin;

-- ---------------------------------------------------------------------------
-- im_cart_items
-- ---------------------------------------------------------------------------
create table if not exists public.im_cart_items (
  id          bigint generated by default as identity primary key,
  user_id     bigint not null references public.im_profiles(id) on delete cascade,
  product_id  bigint not null references public.im_products(id) on delete cascade,
  variant_id  bigint references public.im_product_variants(id) on delete set null,
  quantity    integer not null check (quantity > 0),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique nulls not distinct (user_id, product_id, variant_id)
);
create index if not exists idx_im_cart_user on public.im_cart_items(user_id);
create index if not exists idx_im_cart_product on public.im_cart_items(product_id);

alter table public.im_cart_items enable row level security;

drop policy if exists im_cart_own on public.im_cart_items;
create policy im_cart_own on public.im_cart_items for all
  using (user_id = public.im_current_profile_id())
  with check (user_id = public.im_current_profile_id());

-- ---------------------------------------------------------------------------
-- Map auth.users → im_profiles on signup (buyer/seller from user_metadata).
-- Admin accounts are pre-provisioned via the Admin API + provision script.
-- ---------------------------------------------------------------------------
create or replace function public.im_handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  meta_role text;
  meta_name text;
  clean_role text;
begin
  meta_role := lower(coalesce(new.raw_user_meta_data->>'role', 'buyer'));
  meta_name := nullif(trim(coalesce(new.raw_user_meta_data->>'name', '')), '');
  if meta_role in ('buyer', 'seller', 'admin') then
    clean_role := meta_role;
  else
    clean_role := 'buyer';
  end if;

  insert into public.im_profiles (auth_user_id, name, email, role)
  values (
    new.id,
    coalesce(meta_name, split_part(new.email, '@', 1)),
    lower(new.email),
    clean_role
  )
  on conflict (email) do update
    set auth_user_id = excluded.auth_user_id,
        name = coalesce(nullif(excluded.name, ''), public.im_profiles.name),
        updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.im_handle_new_auth_user();

-- ---------------------------------------------------------------------------
-- Wipe legacy demo marketplace data (keep categories + theme settings).
-- ---------------------------------------------------------------------------
delete from public.im_ticket_responses;
delete from public.im_support_tickets;
delete from public.im_product_reviews;
delete from public.im_order_items;
delete from public.im_orders;
delete from public.im_cart_items;
delete from public.im_product_images;
delete from public.im_product_variants;
delete from public.im_products;
delete from public.im_consent_logs;
delete from public.im_audit_logs;
delete from public.im_ui_prefs;
delete from public.im_profiles;

commit;
