-- IncluMarket — growth-rebuild schema (additive, evolve-in-place).
-- Adds: featured flags, wishlist, order tracking history, flash sales,
-- notifications, newsletter, buyer<->seller messaging, support chatbot.
-- See docs/REBUILD_PLAN.md Phase 1 for the full feature plan this backs.

begin;

-- ---------------------------------------------------------------------------
-- im_products / im_profiles — featured flags
-- ---------------------------------------------------------------------------
alter table public.im_products add column if not exists is_featured boolean not null default false;
create index if not exists idx_im_products_featured on public.im_products(is_featured);

alter table public.im_profiles add column if not exists is_featured_seller boolean not null default false;
alter table public.im_profiles add column if not exists seller_story text;

-- ---------------------------------------------------------------------------
-- im_wishlists
-- ---------------------------------------------------------------------------
create table if not exists public.im_wishlists (
  id         bigint generated by default as identity primary key,
  user_id    bigint not null references public.im_profiles(id) on delete cascade,
  product_id bigint not null references public.im_products(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, product_id)
);
create index if not exists idx_im_wishlists_user    on public.im_wishlists(user_id);
create index if not exists idx_im_wishlists_product on public.im_wishlists(product_id);

-- ---------------------------------------------------------------------------
-- im_order_status_history (buyer-visible tracking timeline; im_orders.order_status
-- stays the current-status column, this is the append-only trail behind it)
-- ---------------------------------------------------------------------------
create table if not exists public.im_order_status_history (
  id         bigint generated by default as identity primary key,
  order_id   bigint not null references public.im_orders(id) on delete cascade,
  status     text not null
               check (status in ('pending','processing','shipped','delivered','returned')),
  note       text,
  created_by bigint references public.im_profiles(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists idx_im_order_history_order on public.im_order_status_history(order_id);

-- ---------------------------------------------------------------------------
-- im_flash_sales
-- ---------------------------------------------------------------------------
create table if not exists public.im_flash_sales (
  id               bigint generated by default as identity primary key,
  product_id       bigint not null references public.im_products(id) on delete cascade,
  discount_percent numeric(5,2) not null check (discount_percent > 0 and discount_percent <= 90),
  starts_at        timestamptz not null default now(),
  ends_at          timestamptz not null,
  created_by       bigint references public.im_profiles(id) on delete set null,
  created_at       timestamptz not null default now(),
  check (ends_at > starts_at)
);
create index if not exists idx_im_flash_sales_product on public.im_flash_sales(product_id);
create index if not exists idx_im_flash_sales_window   on public.im_flash_sales(starts_at, ends_at);

-- ---------------------------------------------------------------------------
-- im_notifications
-- ---------------------------------------------------------------------------
create table if not exists public.im_notifications (
  id         bigint generated by default as identity primary key,
  user_id    bigint not null references public.im_profiles(id) on delete cascade,
  type       text not null check (type in
               ('low_stock','new_order','shipping_update','new_review','flash_sale',
                'order_status','message','chat_escalation','system')),
  title      text not null,
  body       text,
  link       text,
  is_read    boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists idx_im_notifications_user      on public.im_notifications(user_id);
create index if not exists idx_im_notifications_user_read on public.im_notifications(user_id, is_read);

-- ---------------------------------------------------------------------------
-- im_newsletter_subscribers
-- ---------------------------------------------------------------------------
create table if not exists public.im_newsletter_subscribers (
  id              bigint generated by default as identity primary key,
  email           text not null unique,
  subscribed_at   timestamptz not null default now(),
  unsubscribed_at timestamptz,
  source          text
);

-- ---------------------------------------------------------------------------
-- im_conversations + im_messages (buyer <-> seller direct messaging; distinct
-- from im_support_tickets, which is buyer/seller-to-admin support only)
-- ---------------------------------------------------------------------------
create table if not exists public.im_conversations (
  id         bigint generated by default as identity primary key,
  buyer_id   bigint not null references public.im_profiles(id) on delete cascade,
  seller_id  bigint not null references public.im_profiles(id) on delete cascade,
  product_id bigint references public.im_products(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (buyer_id, seller_id)
);
create index if not exists idx_im_conversations_buyer  on public.im_conversations(buyer_id);
create index if not exists idx_im_conversations_seller on public.im_conversations(seller_id);

create table if not exists public.im_messages (
  id              bigint generated by default as identity primary key,
  conversation_id bigint not null references public.im_conversations(id) on delete cascade,
  sender_id       bigint references public.im_profiles(id) on delete set null,
  sender_role     text not null check (sender_role in ('buyer','seller','admin')),
  body            text not null,
  created_at      timestamptz not null default now(),
  read_at         timestamptz
);
create index if not exists idx_im_messages_conversation on public.im_messages(conversation_id);

-- ---------------------------------------------------------------------------
-- im_chat_sessions + im_chat_messages (customer-service chatbot widget).
-- guest_id (client-generated, localStorage) supports pre-auth visitors; a
-- session must belong to a signed-in user OR a guest, never neither.
-- ---------------------------------------------------------------------------
create table if not exists public.im_chat_sessions (
  id                  bigint generated by default as identity primary key,
  user_id             bigint references public.im_profiles(id) on delete set null,
  guest_id            text,
  status              text not null default 'open' check (status in ('open','escalated','closed')),
  escalated_ticket_id bigint references public.im_support_tickets(id) on delete set null,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  check (user_id is not null or guest_id is not null)
);
create index if not exists idx_im_chat_sessions_user  on public.im_chat_sessions(user_id);
create index if not exists idx_im_chat_sessions_guest on public.im_chat_sessions(guest_id);

create table if not exists public.im_chat_messages (
  id         bigint generated by default as identity primary key,
  session_id bigint not null references public.im_chat_sessions(id) on delete cascade,
  role       text not null check (role in ('user','bot','system')),
  body       text not null,
  created_at timestamptz not null default now()
);
create index if not exists idx_im_chat_messages_session on public.im_chat_messages(session_id);

commit;
