-- IncluMarket — Inclusive Market extensions (payment providers, payouts,
-- accessibility prefs, account status, recommendations helpers).
-- Builds on 0005_growth_schema.sql.

begin;

-- ---------------------------------------------------------------------------
-- im_profiles — account status + PWD verification fields (seller onboarding)
-- ---------------------------------------------------------------------------
alter table public.im_profiles
  add column if not exists account_status text not null default 'active'
    check (account_status in ('active','suspended','pending_approval'));
alter table public.im_profiles
  add column if not exists pwd_id_url text;
alter table public.im_profiles
  add column if not exists phone text;

create index if not exists idx_im_profiles_status on public.im_profiles(account_status);
create index if not exists idx_im_profiles_role on public.im_profiles(role);

-- ---------------------------------------------------------------------------
-- im_ui_prefs — expand with Inclusive Market accessibility toolbar prefs
-- (server-side mirror of localStorage keys; client still applies instantly)
-- ---------------------------------------------------------------------------
alter table public.im_ui_prefs
  add column if not exists font_size_px integer not null default 16
    check (font_size_px between 12 and 24);
alter table public.im_ui_prefs
  add column if not exists reduce_motion boolean not null default false;
alter table public.im_ui_prefs
  add column if not exists tts_enabled boolean not null default false;
alter table public.im_ui_prefs
  add column if not exists voice_commands boolean not null default false;
alter table public.im_ui_prefs
  add column if not exists reading_mode boolean not null default false;
alter table public.im_ui_prefs
  add column if not exists highlight_on_read boolean not null default true;
alter table public.im_ui_prefs
  add column if not exists speech_rate numeric(3,2) not null default 1.00
    check (speech_rate between 0.5 and 2.0);
alter table public.im_ui_prefs
  add column if not exists visual_alerts boolean not null default false;
alter table public.im_ui_prefs
  add column if not exists large_cursors boolean not null default false;

-- ---------------------------------------------------------------------------
-- im_payment_providers — admin-configurable multi-provider scaffold
-- ---------------------------------------------------------------------------
create table if not exists public.im_payment_providers (
  id              text primary key
                    check (id in ('paymongo','stripe','paypal','maya','gcash')),
  display_name    text not null,
  enabled         boolean not null default false,
  is_configured   boolean not null default false,
  public_key      text,
  secret_key_hint text,
  dashboard_url   text,
  updated_by      bigint references public.im_profiles(id) on delete set null,
  updated_at      timestamptz not null default now()
);

insert into public.im_payment_providers (id, display_name, enabled, is_configured, dashboard_url)
values
  ('paymongo', 'PayMongo', true,  false, 'https://dashboard.paymongo.com/developers/api-keys'),
  ('stripe',   'Stripe',   false, false, 'https://dashboard.stripe.com/apikeys'),
  ('paypal',   'PayPal',   false, false, 'https://developer.paypal.com/dashboard/applications'),
  ('maya',     'Maya',     false, false, 'https://developers.maya.ph/'),
  ('gcash',    'GCash',    false, false, 'https://www.gcash.com/business')
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- im_payouts — seller payout requests + history
-- ---------------------------------------------------------------------------
create table if not exists public.im_payouts (
  id             bigint generated by default as identity primary key,
  seller_id      bigint not null references public.im_profiles(id) on delete cascade,
  amount         numeric(12,2) not null check (amount > 0),
  method         text not null check (method in ('bank','gcash','maya','paypal','other')),
  account_number text not null,
  status         text not null default 'requested'
                   check (status in ('requested','approved','paid','rejected')),
  note           text,
  processed_by   bigint references public.im_profiles(id) on delete set null,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index if not exists idx_im_payouts_seller on public.im_payouts(seller_id);
create index if not exists idx_im_payouts_status on public.im_payouts(status);

-- ---------------------------------------------------------------------------
-- im_transactions — payment/ledger records for admin reports
-- ---------------------------------------------------------------------------
create table if not exists public.im_transactions (
  id              bigint generated by default as identity primary key,
  order_id        bigint references public.im_orders(id) on delete set null,
  buyer_id        bigint references public.im_profiles(id) on delete set null,
  provider_id     text references public.im_payment_providers(id) on delete set null,
  amount          numeric(12,2) not null check (amount >= 0),
  currency        text not null default 'PHP',
  status          text not null default 'pending'
                    check (status in ('pending','paid','failed','refunded')),
  external_ref    text,
  created_at      timestamptz not null default now()
);
create index if not exists idx_im_transactions_order on public.im_transactions(order_id);
create index if not exists idx_im_transactions_buyer on public.im_transactions(buyer_id);

-- ---------------------------------------------------------------------------
-- im_activity_logs — admin-facing activity feed (complements im_audit_logs)
-- ---------------------------------------------------------------------------
create table if not exists public.im_activity_logs (
  id          bigint generated by default as identity primary key,
  actor_id    bigint references public.im_profiles(id) on delete set null,
  actor_role  text,
  action      text not null,
  entity_type text,
  entity_id   text,
  meta        jsonb,
  created_at  timestamptz not null default now()
);
create index if not exists idx_im_activity_created on public.im_activity_logs(created_at desc);
create index if not exists idx_im_activity_actor on public.im_activity_logs(actor_id);

-- ---------------------------------------------------------------------------
-- im_orders — payment method selected at checkout (provider id)
-- ---------------------------------------------------------------------------
alter table public.im_orders
  add column if not exists payment_provider text
    references public.im_payment_providers(id) on delete set null;
alter table public.im_orders
  add column if not exists shipping_name text;
alter table public.im_orders
  add column if not exists shipping_address text;
alter table public.im_orders
  add column if not exists shipping_phone text;

-- ---------------------------------------------------------------------------
-- Helper view: low-stock variants for seller alerts (computed, not stored)
-- ---------------------------------------------------------------------------
create or replace view public.im_low_stock_alerts as
select
  p.seller_id,
  p.id as product_id,
  p.title as product_title,
  v.id as variant_id,
  v.sku_code,
  v.stock_qty
from public.im_product_variants v
join public.im_products p on p.id = v.product_id
where v.stock_qty <= 5 and p.status = 'approved';

commit;
